# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bad14841be7f13bf5c2d695368c7027cf485b101ba8cd44240dac567a59eada0fe8ab27b3b65e0a34044fcfa98b202dfda45b2012916453058cbafd41420d26

test:
  secret_key_base: a6ff4b124168467d4028c7277d165a041f5745ec72e3b545dac34f037c583834269a84aa8cb13169d75e31ce4cd0c9b3b75ca760c27de8618b510f57d248dccf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
